### ISSUE TITLE
"Warning: stack-setup.yaml: Unrecognized field in SetupInfo: ghcjs"

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1040]
In https://github.com/commercialhaskell/stack/pull/1030 I've added a field for ghcjs tarballs, which will cause this warning in versions of stack that lack the change.  @snoyberg said it'd be fine to go ahead with changing stack-setup-2.yaml: https://github.com/fpco/stackage-content/commit/9ef1c121bef987db3ff370768c52a49072eb8ca5

Since this format is designed to grow (hopefully without too many numeric versions), the `FromJSON` instance shouldn't warn about fields that are unrecognized.

**Comment by borsboom** [comment]
The same instances are used both to load stackage-content/stack-setup-2.yaml, and the `setup-info` field in local stack.yaml.  We should show warnings for the latter, but hide them for the former.  The code that loads the stackage-content/stack-setup-2.yaml can elect to not display the warnings for that case.

**Comment by borsboom** [comment]
Fixed in master.

**Comment by jasonzoladz** [comment]
Still getting this error with latest stack on OSX:

<img width="1029" alt="screen shot 2015-10-02 at 8 19 51 pm" src="https://cloud.githubusercontent.com/assets/8467728/10260392/f909d81e-6942-11e5-9535-e89b1a127ae7.png">
<img width="1037" alt="screen shot 2015-10-02 at 8 19 09 pm" src="https://cloud.githubusercontent.com/assets/8467728/10260394/fd895d74-6942-11e5-84be-9342a63e1907.png">
