### ISSUE TITLE
0.1.6.0 breaks stack-ide

### ISSUE THREAD

**Issue by eallik** [commercialhaskell/stack#1211]
Being on OS X Mavericks **10.9.5**, Emacs for OS X **24.5**, GHC **7.10.2**, after upgrading to **0.1.6.0**, my `stack-ide` installation has ceased to work and instead always just hangs (last message is _"Recompile needed ..."_).

I'm not sure if this is a bug in Stack or stack-ide so I'm filing it here just in case. See also: https://github.com/commercialhaskell/stack-ide/issues/87.

Here's the output comparing **0.1.5.0** and **0.1.6.0**:

```
~/code/haskell/StackStats$ brew switch haskell-stack 0.1.6.0
Cleaning /usr/local/Cellar/haskell-stack/0.1.5.0
Cleaning /usr/local/Cellar/haskell-stack/0.1.6.0
2 links created for /usr/local/Cellar/haskell-stack/0.1.6.0
~/code/haskell/StackStats$ stack ide start
{"tag":"ResponseWelcome","contents":[0,1,1]}
{"tag":"ResponseLog","contents":"[Info] Initializing ide-backend session @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:195:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Session dir = /Users/erik/code/haskell/StackStats/session.8858 @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:208:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Dist dir = /Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:210:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Local working dir = /Users/erik/code/haskell/StackStats/ @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:217:17)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/erik/code/haskell/StackStats/.stack-work/install/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/.stack/snapshots/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/Library/Haskell/bin:/usr/texbin:/Users/erik/.local/bin:/Users/erik/.cabal/bin:/Users/erik/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/erik/.local/bin/ide-backend-server @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:223:5)\n"}
^C{"tag":"ResponseFatalError","contents":"user interrupt"}
Process exited with ExitFailure 1: /Users/erik/.local/bin/stack-ide --verbose --include=/Users/erik/code/haskell/StackStats/:/Users/erik/code/haskell/StackStats/src/:/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/erik/code/haskell/StackStats/:/Users/erik/code/haskell/StackStats/app/:/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/:/Users/erik/code/haskell/StackStats/:/Users/erik/code/haskell/StackStats/test/:/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/:/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --local-work-dir=/Users/erik/code/haskell/StackStats/ --ide-backend-tools-path=/Users/erik/code/haskell/StackStats/.stack-work/install/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/.stack/snapshots/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/Library/Haskell/bin:/usr/texbin:/Users/erik/.local/bin:/Users/erik/.cabal/bin:/Users/erik/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin --dist-dir=/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ --ghc-option=-hide-all-packages --ghc-option=-i/Users/erik/code/haskell/StackStats/ --ghc-option=-i/Users/erik/code/haskell/StackStats/src/ --ghc-option=-i/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package-id=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --ghc-option=-package-id=api-builder-0.11.0.0-4fce63515455b8d34c4b96b2c645fd7e --ghc-option=-package-id=aeson-0.9.0.1-f0ed042b64cecf0538396cfa1b922004 --ghc-option=-package-id=text-1.2.1.3-2395ef415c1b20175aae83b50060e389 --ghc-option=-rtsopts --ghc-option=-with-rtsopts=-N --ghc-option=-i/Users/erik/code/haskell/StackStats/ --ghc-option=-i/Users/erik/code/haskell/StackStats/app/ --ghc-option=-i/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package-id=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --ghc-option=-rtsopts --ghc-option=-with-rtsopts=-N --ghc-option=-i/Users/erik/code/haskell/StackStats/ --ghc-option=-i/Users/erik/code/haskell/StackStats/test/ --ghc-option=-i/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/ --ghc-option=-i/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-stubdir=/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/ --ghc-option=-optP-include --ghc-option=-optP/Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/cabal_macros.h --ghc-option=-package-id=base-4.8.1.0-075aa0db10075facc5aaa59a7991ca2f --package-db=/Users/erik/.stack/snapshots/x86_64-osx/ghc-7.10.2/7.10.2/pkgdb/:/Users/erik/code/haskell/StackStats/.stack-work/install/x86_64-osx/ghc-7.10.2/7.10.2/pkgdb/
~/code/haskell/StackStats$ brew switch haskell-stack 0.1.5.0
Cleaning /usr/local/Cellar/haskell-stack/0.1.5.0
Cleaning /usr/local/Cellar/haskell-stack/0.1.6.0
2 links created for /usr/local/Cellar/haskell-stack/0.1.5.0
~/code/haskell/StackStats$ stack ide start
{"tag":"ResponseWelcome","contents":[0,1,1]}
{"tag":"ResponseLog","contents":"[Info] Initializing ide-backend session @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:195:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Session dir = /Users/erik/code/haskell/StackStats/session.8911 @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:208:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Dist dir = /Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:210:3)\n"}
{"tag":"ResponseLog","contents":"[Debug] Local working dir = /Users/erik/code/haskell/StackStats/ @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:217:17)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/erik/code/haskell/StackStats/.stack-work/install/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/.stack/snapshots/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/Library/Haskell/bin:/usr/texbin:/Users/erik/.local/bin:/Users/erik/.cabal/bin:/Users/erik/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/erik/.local/bin/ide-backend-server @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:223:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Restarting session due to update requiring it. @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:422:11)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusRequiredRestart","contents":[]}}
{"tag":"ResponseLog","contents":"[Info] Restarting ide-backend-server @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update ./IdeSession/Update.hs:351:3)\n"}
{"tag":"ResponseLog","contents":"[Info] Searching for ide-backend-server on this path: /Users/erik/code/haskell/StackStats/.stack-work/install/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/.stack/snapshots/x86_64-osx/ghc-7.10.2/7.10.2/bin/:/Users/erik/Library/Haskell/bin:/usr/texbin:/Users/erik/.local/bin:/Users/erik/.cabal/bin:/Users/erik/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:341:5)\n"}
{"tag":"ResponseLog","contents":"[Info] Found ide-backend-server - using this one: /Users/erik/.local/bin/ide-backend-server @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.RPC.Client ./IdeSession/RPC/Client.hs:343:5)\n"}
{"tag":"ResponseLog","contents":"[Debug] Recompile required, starting... @(ideba_3ZhTR2JwASF9jTa238ZFTP:IdeSession.Update.ExecuteSessionUpdate ./IdeSession/Update/ExecuteSessionUpdate.hs:223:5)\n"}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusProgress","contents":{"progressOrigMsg":"[1 of 2] Compiling Paths_StackStats ( /Users/erik/code/haskell/StackStats/.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/Paths_StackStats.hs, interpreted )","progressStep":1,"progressNumSteps":2,"progressParsedMsg":"Compiling Paths_StackStats"}}}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusProgress","contents":{"progressOrigMsg":"[2 of 2] Compiling Lib              ( /Users/erik/code/haskell/StackStats/src/Lib.hs, interpreted )","progressStep":2,"progressNumSteps":2,"progressParsedMsg":"Compiling Lib"}}}
{"tag":"ResponseUpdateSession","contents":{"tag":"UpdateStatusDone","contents":[]}}
^C{"tag":"ResponseFatalError","contents":"user interrupt"}
```

**Comment by rvion** [comment]
possibly related: https://github.com/commercialhaskell/stack-ide/issues/94

**Comment by mmaz** [comment]
I'm also experiencing this after upgrading to 0.1.6.0 (OSX with the same versions as above), running the latest haskell-mode and flycheck from melpa, and the latest from master on stack-ide.

**Comment by borsboom** [comment]
I just merged a possibly related PR: #1204.  Can you try the latest master?

**Comment by mmaz** [comment]
Hi @borsboom - for me, it seems emacs still hangs on the latest from master (stack version 0.1.7.0, git revision 27b670bf), e.g., when running `M-x stack-mode-info` within a stack project.

**Comment by dbp** [comment]
@mmaz Did you try the fix mentioned in the comment on that issue over at stack-ide: https://github.com/commercialhaskell/stack-ide/issues/87#issuecomment-143470388

Without that, I see the same hanging behavior, but with that fix, stack-ide works for me... With the most current stack and the most current stack-ide...

**Comment by mmaz** [comment]
@dbp I didn't try the fix mentioned there yet. Thanks for the tip though! However, @borsboom or others, should this ticket just be closed since [stack-ide is being deprecated](https://www.fpcomplete.com/blog/2015/10/new-haskell-ide-repo)?

**Comment by borsboom** [comment]
@mgsloan: any ideas about the problem?  Or opinion on whether we should close this issue for now?

**Comment by borsboom** [comment]
Alright, having not heard back, I'll close this for now since the future of stack-ide unclear.  Can re-open later if required.

**Comment by mgsloan** [comment]
Seems like a shame to leave it broken, but I'm not sure what exactly caused it to break.

**Comment by eallik** [comment]
I second mgsloan's point — even though stack-ide will be deprecated, people will most likely be using it for quite a while, and being stuck on 1.5.0 isn't the best option either.

**Comment by mmaz** [comment]
@dbp thanks again for your link to the workaround that @rjmac found. I tried the fix out:

```emacs
;;in stack-ide/stack-mode/stack-mode.el
(setq stack-mode-current-command nil)
```
and emacs didn't hang after I did a type inspection, with 0.1.8.0 :) Really appreciate it!

**Comment by eallik** [comment]
I can confirm the following fix solves the issue:

```diff
  (defun stack-mode-set-initial-command ()
    "Set the initial command callback. The `stack ide` command will
  reload targets on start-up, so that's the default command we'll
  start with."
-   (setq stack-mode-current-command
-         (list :json nil
-               :data nil
-               :cont 'stack-mode-loading-callback
-               :label nil)
-         )
+   ;; (setq stack-mode-current-command
+   ;;       (list :json nil
+   ;;             :data nil
+   ;;             :cont 'stack-mode-loading-callback
+   ;;             :label nil)
+   ;;       )
+   (setq stack-mode-current-command nil)
    (setq stack-mode-queue (stack-fifo-make))
    (stack-mode-log "Set initial command."))
```

**Comment by borsboom** [comment]
Would it be appropriate to make a PR against stack-ide with this change?  Is it actually a fix, or is it just a workaround?  If the latter, is anyone planning to take a stab at fixing it properly?

**Comment by mgsloan** [comment]
A PR to stack-ide with that change would be welcome.  Closing out the issue.
