### ISSUE TITLE
With packages in subdirs, compiler warnings leave subdirectory off file names

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#1259]
I have a package in the subdirectory 'original/'. A compiler warning mentions a file in that package, Mechanism.hs. However, it's listed as "src/Mechanism.hs", not "original/src/Mechanism.hs":

    b@fuzzbomb $ stack test --pedantic
    Snowdrift-0.1.4: build
    Preprocessing library Snowdrift-0.1.4...
    [ 61 of 110] Compiling Mechanism        ( src/Mechanism.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Mechanism.o )

    src/Mechanism.hs:113:1: Warning:
        Top-level binding with no type signature:
          potentialPledge :: forall (m :: * -> *).
                             (MonadResource m, MonadBaseControl IO m, MonadLogger m) =>
                             Key Fixme.User
                             -> ProjectId
                             -> Control.Monad.Trans.Reader.ReaderT
                                  SqlBackend m (Maybe (Entity Pledge), [Int64], [Int64])
    <snip>...

    b@fuzzbomb $ find . -name 'Mechanism.hs'
    ./original/src/Mechanism.hs

**Comment by borsboom** [comment]
I've reproduced.  It looks to me like [this code](https://github.com/commercialhaskell/stack/blob/fecc9340cdf75f35ac2531ae3061713b60827f1f/src/Stack/Build/Execute.hs#L1349) tries to canonicalize the path from the current directory rather than from the package's root directory.  So if you do `cd original; stack test --pedantic` it will show the fully qualified path as expected.

**Comment by borsboom** [comment]
Should now be fixed in master.

**Comment by chreekat** [comment]
Thanks for quick action! Unfortunately I still have the problem. Or, a similar problem.

    $ stack test --pedantic --no-run-tests
    Snowdrift-0.1.4: build
    Preprocessing library Snowdrift-0.1.4...
    [ 61 of 110] Compiling Mechanism        ( src/Mechanism.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Mechanism.o )

    src/Mechanism.hs:113:1: Warning:
        Top-level binding with no type signature:
          potentialPledge :: forall (m :: * -> *).
                             (MonadResource m, MonadBaseControl IO m, MonadLogger m) =>
                             Key Fixme.User
                             -> ProjectId
                             -> Control.Monad.Trans.Reader.ReaderT
                                  SqlBackend m (Maybe (Entity Pledge), [Int64], [Int64])

    <no location info>:
    Failing due to -Werror.
    Progress: 1/2
    --  While building package Snowdrift-0.1.4 using:
          /home/b/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ build lib:Snowdrift exe:Snowdrift exe:SnowdriftEmailDaemon exe:SnowdriftProcessPayments exe:sdm exe:sendmail-mock --ghc-options " -ddump-hi -ddump-to-file"
        Process exited with code: ExitFailure 1
    $ stack --version
    Version 0.1.7.0, Git revision eba1f2bd4ac0deb1bf946d7fb8113536963a20f9 (dirty) (2463 commits) x86_64
    $

**Comment by borsboom** [comment]
Hm, strange.  I actually tested the fix with the Snowdrift repo.

**Comment by chreekat** [comment]
Let me double-triple-confirm, because I appear to be getting different
output sometimes.

**Comment by chreekat** [comment]
Oops, can't do it now. I'll check it tomorrow.

**Comment by borsboom** [comment]
Ok, there was a second issue: it wasn't canonicalizing paths for warnings, only those for errors.  That's now fixed on master as well.

**Comment by chreekat** [comment]
Ah, that was my hunch. Great!
