### ISSUE TITLE
`stack ghci` does not include `extra-lib-dirs` from yaml configuration

### ISSUE THREAD

**Issue by luigy** [commercialhaskell/stack#1656]
and also probably applies to `extra-include-dirs`
assuming that the library and headers exists at the locations listed in the yaml configuration

Expected:
```
> stack ghci
...
Configuring GHCi with the following packages: leveldb-haskell
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
...
Ok, modules loaded: Database.LevelDB, Database.LevelDB.Base, Database.LevelDB.C, Database.LevelDB.Internal, Database.LevelDB.Iterator, Database.LevelDB.MonadResource, Database.LevelDB.Streaming, Database.LevelDB.Types, Data.Stream.Monadic.
*Data.Stream.Monadic Data.Stream.Monadic Database.LevelDB Database.LevelDB.Base Database.LevelDB.C Database.LevelDB.Internal Database.LevelDB.Iterator Database.LevelDB.MonadResource Database.LevelDB.Streaming Database.LevelDB.Types>
```

Actual:
```
> stack ghci
...
Configuring GHCi with the following packages: leveldb-haskell
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (dlopen(libleveldb.dylib, 5): image not found)
Whilst trying to load:  (dynamic) leveldb
Additional directories searched: (none)
```

stack.yaml
```yaml
# /Users/luigy/code/haskell/stack-issues/leveldb-haskell-0.6.3/stack.yaml
resolver: lts-4.1
packages:
- '.'

extra-include-dirs:
  - /Users/luigy/code/haskell/stack-issues/leveldb-haskell-0.6.3/leveldb/include
extra-lib-dirs:
  - /Users/luigy/code/haskell/stack-issues/leveldb-haskell-0.6.3/leveldb
```

```
> stack --version
Version 1.0.1, Git revision 19f00be8bcb6e891f7f627ce3e1164eaa7be19b1 (dirty) (3073 commits) x86_64
```

**Comment by luigy** [comment]
Adding the dirs from yaml configuration to [BuildInfo](https://github.com/commercialhaskell/stack/blob/c7038ddfe366921e551b8ec2f9b3560c28b48ba2/src/Stack/Package.hs#L267) should be enough.  I think cabal-install overwrites what gets passed through the cli, but I'm not sure as to whether we would want to do the same or just union it with what might be there

**Comment by mgsloan** [comment]
We could plumb this info through, and continue doing GHCi the way we have been.  I'd certainly accept a PR that does that, and might write one myself at some point.

However, I think the "correct" way to resolve this stuff is to start pulling this info from the info stored by cabal configure - see #1364 and #970

**Comment by mgsloan** [comment]
A GHC bug which is potentially related: https://ghc.haskell.org/trac/ghc/ticket/11042 Looks like the fix made it into GHC 8

**Comment by crockeea** [comment]
Not sure if this is related, but "stack ghci" also ignores extra-lib-dirs that are modified in a Setup.hs script (though it includes extra-lib-dirs that are written directly in the cabal file).

**Comment by mgsloan** [comment]
@crockeea Yeah, that's tracked by https://github.com/commercialhaskell/stack/issues/970

**Comment by mgsloan** [comment]
Fixed! Tested on https://github.com/expipiplus1/simple-shared , and what didn't work before works now!

**Comment by leohaskell** [comment]
@mgsloan, `ghci` now respects the --extra-lib-dirs, but those still can't be set from Setup.hs (from preConf or preRepl). That wouldn't be a problem if relative paths could be used in --extra-lib-dirs, but since they couldn't, they must be set manually using the hooks. Any plans on fixing that too?

**Comment by leohaskell** [comment]
@mgsloan, great! Thank you for your efforts!
