### ISSUE TITLE
Stack setup fails to install ghc on NixOS

### ISSUE THREAD

**Issue by tdimiduk** [commercialhaskell/stack#2586]
Stack is failing to install ghc 7.10 for me on NixOS unstable. I have ghc 8.0.1 installed as my default ghc:
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
But stack wants to use 7.10
$ stack new test
<snip>
Downloaded lts-6.17 build plan.    
Did not find .cabal file for servant-yaml-0.1.0.0 with Git SHA of 71c0a55d0a877954d9590e285c0eb861ace2d8cc
Right Nothing
* Matches lts-6.17

Selected resolver: lts-6.17
Initialising configuration using resolver: lts-6.17
Total number of user packages considered: 1
Writing configuration to file: test/stack.yaml
All done.

$ cd test
$ stack setup
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                 
Running /tmp/stack-setup3673/ghc-7.10.3/configure --prefix=/home/tdimiduk/.stack/programs/x86_64-linux/ghc-7.10.3/ in directory /tmp/stack-setup3673/ghc-7.10.3/ exited with ExitFailure 1

checking for path to top of build tree... 
utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: line 3: /tmp/stack-setup3673/ghc-7.10.3/utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: No such file or directory
configure: error: cannot determine current directory

It looks like the ghc-pwd binary wants to dynamically link against libraries I do not have present, and thus is failing, preventing stack from installing its local version of ghc 7.10.

**Comment by tdimiduk** [comment]
I have determined a workaround, I can use a nix-shell with the correct ghc:
$ nix-shell -p haskell.compiler.ghc7103
and then I can run stack build just fine on packages using lts's needing ghc 7.10.

So this issue may be unnecessary, feel free to close it, but at least this way hopefully a workaround to this issue will be googleable.

**Comment by domenkozar** [comment]
This was documented in recent Stack release, but I wonder if the error message should be clearer.

**Comment by tdimiduk** [comment]
I clearer error message would have saved me a chunk of time, so I would be
in favor.

**Comment by mgsloan** [comment]
Based on this comment by @YPares - https://github.com/commercialhaskell/stack/issues/1882#issuecomment-194180059 - `stack setup` should be unnecessary and perhaps harmful with nix.  I have split off this issue to track that conclusion - https://github.com/commercialhaskell/stack/issues/2634

**Comment by YPares** [comment]
@mgsloan Unnecessary but it shouldn't be harmful. I'll have a look tomorrow.

**Comment by YPares** [comment]
@mgsloan After a closer look, it's actually different. @tdimiduk doesn't have nix support activated, or else he wouldn't see:
```
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
```
as this only happens when nix is deactivated.

**Comment by mgsloan** [comment]
@YPares Ah, interesting!  So using NixOS but not using stack with nix support.  Re-opening the ticket.

**Comment by domenkozar** [comment]
I don't see how compiling GHC on NixOS with stack would work or make sense, but could be supported if needed.

**Comment by tdimiduk** [comment]
I was not trying to compile GHC, I was just trying to use stack but not
with the stack nix support.

When I tried to use stack -nix it didn't work, and something led me to the
(it appears erroneous) conclusion that nix support was deprecated and
broken and so I should just try to use normal stack.

If stack -nix is still the suggested way to use stack on nixos, then feel
free to close this issue and I will refile a different one when I get a
chance to figure out what was breaking with stack -nix for me.

**Comment by ElvishJerricco** [comment]
Yea I've run into this. The problem is that the binaries for GHC use a regular Linux FHS dynamic linker, but NixOS doesn't have a dynamic linker in that location. This is why binaries are hit with `patchelf` when installed with Nix; to get them to use the local dynamic linker. This error occurs because `ghc-pwd` can't be executed, since it fails to find the dynamic linker

```
utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: line 3: /tmp/stack-setup3673/ghc-7.10.3/utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: No such file or directory
configure: error: cannot determine current directory
```

Luckily, nix integration finally works with stack 1.2.0. But I don't think that version of stack is on any `nixpkgs` channel, so it has to be installed manually. Also, this doesn't solve the issues with GHCJS. Stack doesn't let you build with a non-GHC compiler using nix integration, so you have to try it without nix integration, leading to the dynamic linker problem again when installing GHC for compiling GHCJS.

**Comment by domenkozar** [comment]
Stack 1.2.0 will hit channels as soon as last test blocker is fixed: http://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents

**Comment by tdimiduk** [comment]
Sounds good. I will consider this resolved then.

**Comment by ElvishJerricco** [comment]
I'm not sure I'd consider this fully resolved, since this problem still affects anyone trying to use GHCJS? Maybe that should be a separate issue though.
