### ISSUE TITLE
stack is slow

### ISSUE THREAD

**Issue by s-trooper** [commercialhaskell/stack#274]
Win7 x64: "stack runghc Hello.hs", "stack exec hello" i suppose "stack" itself bring performance penalty over 1 s that is real a problem if to use stack in scripting case. Here some data:

hello.exe                      0.065 s
stack exec hello          1.090 s

runghc Main.hs           0.333 s
stack runghc Main.hs  1.387 s

sure stack need time but for special cases it should bypass things like runghc ... :)

**Comment by snoyberg** [comment]
We purposely have avoided optimizations till this point (premature optimizations and all that), but would like to address this properly for the first release. I know of at least one piece of low-hanging fruit in this regard: #213. If you (or someone else) is interested in attacking this, let me know. Using the `-v` option should give a good idea of where time is being spent.

**Comment by s-trooper** [comment]
stack is the tool that convince/allow me to use haskell in my company. just now i am writing on my first "hello world", not the best reference for performance optimization i guess :)

**Comment by snoyberg** [comment]
Awesome, I'm glad to hear it!

**Comment by snoyberg** [comment]
I got rid of a silly performance regression I added today, in e01cba4a38fbd4737c4dfde0a123894edbbc4892. Numbers are much better now:

```
$ time runghc Main.hs
Hello World

real    0m0.184s
user    0m0.096s
sys     0m0.088s

$ time stack exec runghc Main.hs
Hello World

real    0m0.325s
user    0m0.192s
sys     0m0.280s
```

Some overhead is inevitable, as stack needs to parse config files, query GHC for package databases, and a few other things. But this is at least a much more reasonable overhead. I'm sure there are more places we can optimize as we get towards the end of beta.

**Comment by ndmitchell** [comment]
Investigating on my work machine, it seems that each process spawned by anything takes 0.3s, due to a very aggressive (aka stupid) antivirus policy. I suspect this problem will be rare on developer machines, but more common in corporate environments. As a result, anything you can do to avoid spawning processes (caching `ghc-pkg list` calls, spawning `ghc --interactive` directly instead of `ghci` with `stack ghci`) is likely to produce meaningful speedups. Cabal is particularly bad for spawning loads of processes with `cabal configure`.

**Comment by snoyberg** [comment]
I think this is mostly resolved now, though performance improvements in the future will certainly be on the table. I'm going to close for now, please do report any regressions noticed.

**Comment by 2chilled** [comment]
Outside of a stack project:
```
time stack exec echo 'hello'
Run from outside a project, using implicit global project config
Using resolver: lts-7.2 from implicit global project's config file: ~/.stack/global-project/stack.yaml
hello

real	0m0.385s
user	0m0.459s
sys	0m0.070s
```
Inside a small stack project
```
time stack exec echo 'hello'
hello

real    0m3.643s
user    0m3.620s
sys     0m0.135s
```
Any ideas to make this faster? Dev tools like hdevtools using stack to do their job consume very most of their time waiting for stack, which is unfortunate.

I use stack Version 1.2.0 x86_64

**Comment by domenkozar** [comment]
It seems the issue is back:

https://github.com/commercialhaskell/stack/issues/2885
