### ISSUE TITLE
Less frequent test builds WAS stack test does not rebuild

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#319]
There seems to be major issues with `stack test` not re-building right now. It does not rebuild the test section when I make a change. An extreme example of this behavior is that I had a compilation failure in my tests and then when I run `stack test` a second time I see `Test suite executable not found for ...`

**Comment by gregwebs** [comment]
Version 0.0.2, Git revision 115972b9a2946b247482035be71fe269081a5640

**Comment by snoyberg** [comment]
Ugh, I know what the problem is, hold on.

**Comment by snoyberg** [comment]
I temporarily disabled some dirtiness checking code in the test and bench building, and am forcing a rebuild each time. Can you try out master now to confirm that I was right about where the problem came from?

**Comment by gregwebs** [comment]
yes, that seems to work now

**Comment by snoyberg** [comment]
Alright, determined the original problem: Stack.Package doesn't list test suite and benchmark files for dirtiness checking. @chrisdone and I are discussing how best to determine that information.

**Comment by snoyberg** [comment]
For some reason I'm getting stuck figuring out the right way to do this without forcing a `runghc Setup.hs build` each time. I'm going to defer to a later milestone as an optimization.

**Comment by spinda** [comment]
I noticed that `stack test` doesn't rebuild the test runner if its source has changed from when it was first built. Is this the same issue or a different one?

**Comment by gregwebs** [comment]
what version of `stack` are you using?

**Comment by spinda** [comment]
Ah, I forgot I was still on `stack-0.0.2.1`. Switching to the latest `stack` fixed my problem.

**Comment by snoyberg** [comment]
I've just pushed a commit that should make it so that tests are only rebuilt when necessary. I _think_ the problems we were seeing previously with this code have been resolved, but I'd appreciate some testing by others to confirm. @gregwebs can you test out master?

**Comment by spinda** [comment]
I'm still seeing `stack test` do full rebuilds immediately after completing a `stack build`.

**Comment by snoyberg** [comment]
@spinda Can you clarify what you mean by full rebuild, or rather, what exact steps you're running? And are you using the latest master?

**Comment by snoyberg** [comment]
I think the original issue is resolved. If there are problems, please report in a new issue to avoid confusion.

**Comment by gregwebs** [comment]
Things seem to be working pretty smoothly now with switching between `stack build` and `stack test`.
