### ISSUE TITLE
Extensible snapshots don't pick up git dependencies correctly

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#3299]
### General summary/comments (optional)

When I move a git dependency from `stack.yaml` to a snapshot, the git version no longer takes precedence over the underlying lts snapshot.

### Steps to reproduce

I put an example at https://github.com/feuerbach/stack-snapshots-bug. There are two tags; v1 builds, but v2 fails, because it uses an older version of algebraic-graphs (presumably from lts) that lacks the `dfsForestFrom` function.

[Full session log](https://github.com/feuerbach/stack-snapshots-bug/blob/master/session.txt)

### Stack version

```
Version 1.5.1, Git revision a4f1a9f5f2907d5b13d72429b4f0fc2d5fb4e3ce (5011 commits) x86_64 hpack-0.17.1
```

### Method of installation

from git master

**Comment by snoyberg** [comment]
I'll look into this in the next few days hopefully, I have a few other extensible snapshot issues to look at first.

**Comment by snoyberg** [comment]
I have a feeling this is a slightly different bug than you think it is, since I'm unable to reproduce it. I'm currently working on fixing some issues around snapshot packages not rebuilding correctly, which I _think_ is the thing you're running into. When I do a clean clone of your repo and run `stack build`, it works for me. I haven't been able to trigger the bug with any combination of `checkout`s. Can you try wiping out `.stack-work` and see if it fixes the build?

Bonus points: if that does in fact work, and you're able to provide a set of repro steps from a clean repo, that would be great, it will help me debug the bigger issue that I think you're suffering from here.

My stack:

```
$ stack --version
Version 1.5.1, Git revision b55cd0471ec0961258e5270354be0548047c7176 (dirty) (5028 commits) x86_64 hpack-0.17.1
```

**Comment by feuerbach** [comment]
But the session log I published above *was* from a clean repo checkout. The first command there is git clone.

The custom snapshot name was not fresh — does stack cache builds globally based on that name?

I'll try with your version of stack.

**Comment by snoyberg** [comment]
Ah, good point. Let me know how the test with the new version goes. I'd be surprised if I've fixed this by mistake though, I don't think the relevant code has changed much.

No, stack cache does _not_ work based on name, it works on a hash of the file contents, which will implicitly include the Git SHAs as well.

**Comment by feuerbach** [comment]
Still failing here, with your version of stack, after doing `stack clean` and removing the snapshot cache directory. [Here's the log.](https://github.com/feuerbach/stack-snapshots-bug/blob/master/session2.txt)

**Comment by snoyberg** [comment]
Still having trouble reproing. One thought I had is that this could be due to preexisting packages in the lts-8.11 snapshot, but that doesn't seem to be relevant.

Could you paste the output of `stack exec -- ghc-pkg list`?

**Comment by feuerbach** [comment]
> One thought I had is that this could be due to preexisting packages in the lts-8.11 snapshot

Yes, that's what I was referring to as well when I wrote

> the git version no longer takes precedence over the underlying lts snapshot

Outputs of ghc-pkg list: [v1 (succeeding, no extensible snapshots)](https://github.com/feuerbach/stack-snapshots-bug/blob/master/ghc-pkg-list-v1.txt), [v2 (failing, extensible snapshots)](https://github.com/feuerbach/stack-snapshots-bug/blob/master/ghc-pkg-list-v2.txt)

**Comment by feuerbach** [comment]
Could you be unable to reproduce because your lits-8.11 does not contain a compiled version of algebraic-graphs?

**Comment by snoyberg** [comment]
I tried installing it and still couldn't repro.

Thanks for the looks, I'll investigate later (afk now).

**Comment by snoyberg** [comment]
The second dump seems to imply pretty strongly that there is no other version of `algebraic-graphs` lying around. Very curious, and especially disconcerting that I can't reproduce. In any event, I _am_ able to reproduce a possibly related bug (not rebuilding extra-deps), and am working on an overhaul for that. I'll ping you when that is PR-ready (may not be for a few days), it'll be interesting if that fixes this.

**Comment by feuerbach** [comment]
I tried creating a fresh user and building there, and indeed I could not reproduce this.

Then I copied my `~/.stack` into the new user's home directory, and the bug reappeared.

So, if you think it is important to investigate this, I could give you my `~/.stack`.

Or I could erase my ~/.stack, the issue will probably go away, and we can close this.

**Comment by feuerbach** [comment]
Also, erasing only `~/.stack/snapshots/` makes the bug go away, so it probably has something to do with the precompiled packages.

**Comment by snoyberg** [comment]
I'd like to get to the bottom of it, but analyzing the `~/.stack` dir probably won't work very well.

I've pushed a commit (still half-broken) that at least tracks dirtiness a little bit better. Could you try it? It's 867f59ea248fef3e3d3a4ee2630d92aa0befe084 on the `gut-upstreams` branch.

If this doesn't work, the call is yours whether to continue testing new versions to see if they fix it, or just drop the whole thing.

**Comment by feuerbach** [comment]
No, that didn't help. I don't mind testing new versions, and maybe I'll find the time to look into it myself.

**Comment by feuerbach** [comment]
So, I don't see how this is supposed to work. 

Look at [session2.txt](https://github.com/feuerbach/stack-snapshots-bug/blob/master/session2.txt):

```
2017-08-01 14:15:26.744973: [debug] Exception ignored when attempting to load /home/feuerbach/.stack/loaded-snapshot-cache/x86_64-linux/ghc-8.0.2/custom-test-snapshot-sgEuTDdfyeOX.cache: /home/feuerbach/.stack/loaded-snapshot-cache/x86_64-linux/ghc-8.0.2/custom-test-snapshot-sgEuTDdfyeOX.cache: openBinaryFile: does not exist (No such file or directory)
@(Data/Store/VersionTagged.hs:84:9)
2017-08-01 14:15:26.745058: [debug] Failure decoding /home/feuerbach/.stack/loaded-snapshot-cache/x86_64-linux/ghc-8.0.2/custom-test-snapshot-sgEuTDdfyeOX.cache
@(Data/Store/VersionTagged.hs:73:13)
```

stack detects that there is no custom snapshot cache (as I removed it).

After this, it would be logical for stack to build algebraic-graphs; but there is not indication of that. The nearest compilation step is of the target package itself, specifying `--dependency=algebraic-graphs=algebraic-graphs-0.0.4-3zHm8QPVeBsBWAhDQStOLS`. How can that be explained?

Moreover,

```
% stack --resolver=lts-8.11 exec ghc-pkg list -- -v algebraic-graphs                                                                                                                         
GHC package manager version 8.0.2
Timestamp 2017-08-02 10:54:15.396385957 UTC for /home/feuerbach/.stack/global/.stack-work/install/x86_64-linux/lts-8.11/8.0.2/pkgdb/package.cache
Timestamp 2017-08-02 10:54:15.396385957 UTC for /home/feuerbach/.stack/global/.stack-work/install/x86_64-linux/lts-8.11/8.0.2/pkgdb (same as cache)
using cache: /home/feuerbach/.stack/global/.stack-work/install/x86_64-linux/lts-8.11/8.0.2/pkgdb/package.cache
Timestamp 2017-07-26 05:03:59.954312775 UTC for /home/feuerbach/.stack/snapshots/x86_64-linux/lts-8.11/8.0.2/pkgdb/package.cache
Timestamp 2017-07-26 05:03:59.954312775 UTC for /home/feuerbach/.stack/snapshots/x86_64-linux/lts-8.11/8.0.2/pkgdb (same as cache)
using cache: /home/feuerbach/.stack/snapshots/x86_64-linux/lts-8.11/8.0.2/pkgdb/package.cache
Timestamp 2017-04-06 08:14:33.530895115 UTC for /home/feuerbach/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache
Timestamp 2017-04-06 08:14:33.505894921 UTC for /home/feuerbach/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d (older than cache)
using cache: /home/feuerbach/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d/package.cache
db stack: ["/home/feuerbach/.stack/global/.stack-work/install/x86_64-linux/lts-8.11/8.0.2/pkgdb","/home/feuerbach/.stack/snapshots/x86_64-linux/lts-8.11/8.0.2/pkgdb","/home/feuerbach/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d"]
modifying: Nothing
flag db stack: ["/home/feuerbach/.stack/global/.stack-work/install/x86_64-linux/lts-8.11/8.0.2/pkgdb","/home/feuerbach/.stack/snapshots/x86_64-linux/lts-8.11/8.0.2/pkgdb","/home/feuerbach/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d"]
/home/feuerbach/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d
    (no packages)
/home/feuerbach/.stack/snapshots/x86_64-linux/lts-8.11/8.0.2/pkgdb
    algebraic-graphs-0.0.4 (algebraic-graphs-0.0.4-3zHm8QPVeBsBWAhDQStOLS)
/home/feuerbach/.stack/global/.stack-work/install/x86_64-linux/lts-8.11/8.0.2/pkgdb
    (no packages)
```

The ghc hash of algebraic-graph in lts-8.11 is the same as was passed to the target package during the build.

**Comment by snoyberg** [comment]
> How can that be explained?

The file you removed is a binary cache of the snapshot definition itself. You haven't removed any of the compiled packages themselves. Stack is regenerating the binary cache of the snapshot definition, and then discovering the old library build and using it.

I wonder if this is at all related to the change in behavior with package IDs in Cabal. It used to be that generated package IDs depended on the package contents, but they are now simply aliases for the package key. Here's the issue I raised upstream:

https://github.com/haskell/cabal/issues/4381

**Comment by feuerbach** [comment]
> Stack is regenerating the binary cache of the snapshot definition, and then discovering the old library build and using it.

Does that build come from the base snapshot (lts-8.11 in my case)?

If yes, how does stack check that that build corresponds to the specific git revision I requested?

If no, where is the old library build stored?

**Comment by snoyberg** [comment]
No, it's not coming from lts-8.11 at all (or shouldn't be). It's coming from a directory like:

```
~/.stack/snapshots/x86_64-osx/custom-snapshot-BScKOT9lJ7Y3/8.0.2
```

From your log, it looks like it's using:

    /home/feuerbach/.stack/snapshots/x86_64-linux/custom-test-snapshot-sgEuTDdfyeOX/8.0.2/pkgdb

**Comment by feuerbach** [comment]
Ok, got it. After removing that directory, it all seems to work fine. So I guess it's safe to close this.
