### ISSUE TITLE
Unable to build hackage package: Failed to load interface

### ISSUE THREAD

**Issue by eddieschoute** [commercialhaskell/stack#3560]
### General summary/comments
Installing the hackage package `easyrender` throws errors for loading interfaces.

### Steps to reproduce

1. Create a new stack project (eg `stack new my-project`)
2. Add dependency to `easyrender` in the project cabal file library>build-depends
3. Add `superdoc-0.1.2.4` and `easyrender-0.1.1.2` to the stack.yaml>packages
4. Run command `stack build`.

Config files with add .txt for GitHub upload:
[easyrender-bug.cabal.txt](https://github.com/commercialhaskell/stack/files/1450785/easyrender-bug.cabal.txt)
[stack.yaml.txt](https://github.com/commercialhaskell/stack/files/1450787/stack.yaml.txt)

### Expected

I expect the package to build successfully.
Installing easyrender through cabal install completes successfully.

### Actual

The build process throws an error about not being able to find an interface.

```
~/dev/easyrender-bug> stack build --verbose
Version 1.5.1 x86_64 hpack-0.17.1
2017-11-07 11:31:56.837897: [debug] Checking for project config at: /Users/eddie/dev/easyrender-bug/stack.yaml
@(Stack/Config.hs:974:9)
2017-11-07 11:31:56.872875: [debug] Loading project config file stack.yaml
@(Stack/Config.hs:999:13)
2017-11-07 11:31:56.883745: [debug] Trying to decode /Users/eddie/.stack/build-plan-cache/x86_64-osx/lts-9.12.cache
@(Data/Store/VersionTagged.hs:72:5)
2017-11-07 11:31:56.896491: [debug] Success decoding /Users/eddie/.stack/build-plan-cache/x86_64-osx/lts-9.12.cache
@(Data/Store/VersionTagged.hs:76:13)
2017-11-07 11:31:56.896828: [debug] Using standard GHC build
@(Stack/Setup.hs:606:9)
2017-11-07 11:31:56.897416: [debug] Asking GHC for its version
@(Stack/Setup/Installed.hs:103:13)
2017-11-07 11:31:56.897718: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --numeric-version
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:56.897803: [debug] Getting Cabal package version
@(Stack/GhcPkg.hs:189:5)
2017-11-07 11:31:56.897979: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --no-user-package-db field --simple-output Cabal version
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:56.898628: [debug] Getting global package database location
@(Stack/GhcPkg.hs:55:5)
2017-11-07 11:31:56.898694: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --no-user-package-db list --global
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:56.941275: [debug] Process finished in 42ms: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --no-user-package-db list --global
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:56.946097: [debug] Process finished in 48ms: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --no-user-package-db field --simple-output Cabal version
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:56.970987: [debug] Process finished in 73ms: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --numeric-version
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:56.971165: [debug] Resolving package entries
@(Stack/Setup.hs:260:5)
2017-11-07 11:31:56.971548: [debug] Starting to execute command inside EnvConfig
@(Stack/Runners.hs:175:18)
2017-11-07 11:31:56.971698: [debug] Parsing the cabal files of the local packages
@(Stack/Build/Source.hs:328:5)
2017-11-07 11:31:56.973088: [debug] Parsing the targets
@(Stack/Build/Source.hs:265:5)
2017-11-07 11:31:56.973487: [debug] Exception ignored when attempting to load /Users/eddie/dev/easyrender-bug/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/stack-build-cache: /Users/eddie/dev/easyrender-bug/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/stack-build-cache: openBinaryFile: does not exist (No such file or directory)
@(Data/Store/VersionTagged.hs:90:9)
2017-11-07 11:31:56.973784: [debug] Start: getPackageFiles /Users/eddie/dev/easyrender-bug/easyrender-bug.cabal
@(Stack/Package.hs:259:21)
2017-11-07 11:31:56.996824: [debug] Finished in 1ms: getPackageFiles /Users/eddie/dev/easyrender-bug/easyrender-bug.cabal
@(Stack/Package.hs:259:21)
2017-11-07 11:31:57.004282: [debug] Finding out which packages are already installed
@(Stack/Build/Installed.hs:69:5)
2017-11-07 11:31:57.004660: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --global --no-user-package-db dump --expand-pkgroot
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.048816: [debug] Process finished in 44ms: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --global --no-user-package-db dump --expand-pkgroot
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.065936: [debug] Ignoring package haskeline due to wanting version 0.7.4.0 instead of 0.7.3.0
@(Stack/Build/Installed.hs:199:5)
2017-11-07 11:31:57.066055: [debug] Ignoring package terminfo due to wanting version 0.4.1.0 instead of 0.4.0.2
@(Stack/Build/Installed.hs:199:5)
2017-11-07 11:31:57.066103: [debug] Ignoring package xhtml due to wanting version 3000.2.2 instead of 3000.2.1
@(Stack/Build/Installed.hs:199:5)
2017-11-07 11:31:57.066346: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --user --no-user-package-db --package-db /Users/eddie/.stack/snapshots/x86_64-osx/lts-9.12/8.0.2/pkgdb dump --expand-pkgroot
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.103818: [debug] Process finished in 37ms: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --user --no-user-package-db --package-db /Users/eddie/.stack/snapshots/x86_64-osx/lts-9.12/8.0.2/pkgdb dump --expand-pkgroot
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.104146: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --user --no-user-package-db --package-db /Users/eddie/dev/easyrender-bug/.stack-work/install/x86_64-osx/lts-9.12/8.0.2/pkgdb dump --expand-pkgroot
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.141462: [debug] Process finished in 37ms: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --user --no-user-package-db --package-db /Users/eddie/dev/easyrender-bug/.stack-work/install/x86_64-osx/lts-9.12/8.0.2/pkgdb dump --expand-pkgroot
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.142021: [debug] Trying to decode /Users/eddie/.stack/indices/Hackage/01-index.cache
@(Data/Store/VersionTagged.hs:72:5)
2017-11-07 11:31:57.361791: [debug] Success decoding /Users/eddie/.stack/indices/Hackage/01-index.cache
@(Data/Store/VersionTagged.hs:76:13)
2017-11-07 11:31:57.374018: [debug] Constructing the build plan
@(Stack/Build/ConstructPlan.hs:188:5)
2017-11-07 11:31:57.397804: [debug] Checking if we are going to build multiple executables with the same name
@(Stack/Build.hs:210:5)
2017-11-07 11:31:57.398443: [debug] Executing the build plan
@(Stack/Build/Execute.hs:478:5)
2017-11-07 11:31:57.399336: [debug] Getting global package database location
@(Stack/GhcPkg.hs:55:5)
2017-11-07 11:31:57.399407: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --no-user-package-db list --global
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.435576: [debug] Process finished in 36ms: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-pkg --no-user-package-db list --global
@(System/Process/Read.hs:306:3)
2017-11-07 11:31:57.441729: [debug] Exception ignored when attempting to load /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/stack-config-cache: /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/stack-config-cache: openBinaryFile: does not exist (No such file or directory)
@(Data/Store/VersionTagged.hs:90:9)
2017-11-07 11:31:57.442097: [debug] Exception ignored when attempting to load /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/stack-cabal-mod: /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/stack-cabal-mod: openBinaryFile: does not exist (No such file or directory)
@(Data/Store/VersionTagged.hs:90:9)
2017-11-07 11:31:57.442395: [info] easyrender-0.1.1.2: configure
@(Stack/Build/Execute.hs:830:23)
2017-11-07 11:31:57.443372: [debug] Run process: /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc-8.0.2 --make -odir /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup -hidir /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup -i -i. -clear-package-db -global-package-db -package-db=/Users/eddie/.stack/snapshots/x86_64-osx/lts-9.12/8.0.2/pkgdb -package-db=/Users/eddie/dev/easyrender-bug/.stack-work/install/x86_64-osx/lts-9.12/8.0.2/pkgdb -hide-all-packages -package-id=base-4.9.1.0 -package-id=superdoc-0.1.2.4-EyLru7f81IU7QNv901wuQl -optP-include -optP/private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup_macros.h /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/Setup.hs /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup -threaded
@(System/Process/Read.hs:340:3)
Progress: 1/2
--  While building package easyrender-0.1.1.2 using:
      /Users/eddie/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc --make -odir /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup -hidir /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup -i -i. -clear-package-db -global-package-db -package-db=/Users/eddie/.stack/snapshots/x86_64-osx/lts-9.12/8.0.2/pkgdb -package-db=/Users/eddie/dev/easyrender-bug/.stack-work/install/x86_64-osx/lts-9.12/8.0.2/pkgdb -hide-all-packages -package-id=base-4.9.1.0 -package-id=superdoc-0.1.2.4-EyLru7f81IU7QNv901wuQl -optP-include -optP/private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup_macros.h /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/Setup.hs /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -main-is StackSetupShim.mainOverride -o /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup -threaded
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/eddie/dev/easyrender-bug/.stack-work/logs/easyrender-0.1.1.2.log

    [1 of 2] Compiling Main             ( /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/Setup.hs, /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/bc/q4cgygts2m79w62j_93vdyww0000gn/T/stack15445/easyrender-0.1.1.2/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/StackSetupShim.o )
    
    /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:3:1: error:
        Failed to load interface for ‘Distribution.PackageDescription’
        It is a member of the hidden package ‘Cabal-1.24.2.0’.
        Use -v to see a list of the files searched for.
    
    /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:4:1: error:
        Failed to load interface for ‘Distribution.Simple’
        It is a member of the hidden package ‘Cabal-1.24.2.0’.
        Use -v to see a list of the files searched for.
    
    /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:5:1: error:
        Failed to load interface for ‘Distribution.Simple.Build’
        It is a member of the hidden package ‘Cabal-1.24.2.0’.
        Use -v to see a list of the files searched for.
    
    /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:6:1: error:
        Failed to load interface for ‘Distribution.Simple.Setup’
        It is a member of the hidden package ‘Cabal-1.24.2.0’.
        Use -v to see a list of the files searched for.
    
    /Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:7:1: error:
        Failed to load interface for ‘Distribution.Simple.LocalBuildInfo’
        It is a member of the hidden package ‘Cabal-1.24.2.0’.
        Use -v to see a list of the files searched for.
```

### Stack version

```
~/dev/easyrender-bug> stack --version
Version 1.5.1 x86_64 hpack-0.17.1
```

### Method of installation

Installed through OSX brew

**Comment by mgsloan** [comment]
Huh, I wonder what could be going wrong there.  Might be worthwhile trying:

* Upgrade to stack-1.6 pre release via https://github.com/commercialhaskell/stack/releases/tag/v1.6.0.20171022 .  Would be curious if this fixes it.

* May help to update Cabal version via `stack setup --upgrade-cabal`

**Comment by eddieschoute** [comment]
I have tried the following:

1. Try version 1.6 by moving ~/.stack to a different location and then using the referenced binary to `stack build` the easyrender-bug project that I used above.
2. Upgrading cabal does not help, it says that I already have the newest version.

**Comment by mgsloan** [comment]
> Upgrading cabal does not help, it says that I already have the newest version.

Hmm, yeah, that was a bit of a long shot too.  Do the mentions of `Cabal` in `stack path` say version 2?

Not sure how to fix.  Using the gold linker might help, but there isn't a convenient way to do that for all the packages in the snapshot.  Need to fix that issue - https://github.com/commercialhaskell/stack/issues/2938 https://github.com/commercialhaskell/stack/issues/3128

**Comment by mgsloan** [comment]
@eddieschoute Oh wow!  Glad you opened this issue.  Looks like there was a logic bug in the `--upgrade-cabal` code in stack-1.5.  I've fixed it.  So, first due `stack upgrade --git`, then `stack setup --upgrade-cabal`.

Still, no idea if this will resolve the issue, but worth a shot!  At least the problem --upgrade-cabal is fixed.

**Comment by eddieschoute** [comment]
Awesome, I have upgraded my version as instructed:
```
~/dev/easyrender-bug> stack path | grep -I cabal
dist-dir: .stack-work/dist/x86_64-osx/Cabal-2.0.0.2
```

It did not resolve the issue, but the errors have changed slightly:
```
/Users/eddie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs:3:1: error:
    Failed to load interface for ‘Distribution.PackageDescription’
    It is a member of the hidden package ‘Cabal-2.0.0.2’.
    It is a member of the hidden package ‘Cabal-1.24.2.0’.
    Use -v to see a list of the files searched for.
```
(Full output of `stack build-v ` [stackbuild.log](https://github.com/commercialhaskell/stack/files/1461836/stackbuild.log) )

**Comment by mgsloan** [comment]
Looks like easyrender's `setup-depends` needs to mention Cabal.  Looks like caba new-build has a similar problem - https://github.com/haskell/cabal/issues/4288 .  Though, I couldn't get it to build easyrender at all because cabal-install picked dependencies that don't work together.

So, suggested workaround is to:

* clone easyrender to a sub-directory, and add it to your packages list.

* Add Cabal to its `setup-depends:`

* Open a PR against the package.

**Comment by eddieschoute** [comment]
I am able to build the project by

1. Placing the extracted `easyrender-0.1.1.2` in the project root.
2. Adding `superdoc-0.1.1.2` with `extra-deps: true` to the `stack.yaml` and removing its entry from `extra-deps`.
3. Modifying the superdoc cabal file, by changing `cabal-version: >= 1.24` and adding `custom-setup` rules to the cabal file:
```
custom-setup
  setup-depends:
    base >= 4.5,
    Cabal >= 1.24 && < 2,
    superdoc >= 0.1
```

What would you suggest to the easyrender package. Should they include setup dependencies (in accordance with http://cabal.readthedocs.io/en/latest/developing-packages.html#custom-setup-scripts)?

**Comment by mgsloan** [comment]
Yes, the easyrender package should include Cabal in its setup dependencies in order to support build tools.  It is unclear to me whether cabal will make this dependency implicit.  I guess old build makes it implicit and new-build does not..
