### ISSUE TITLE
qAddDependentFile doesn't cause re-compilation without extra-source-files

### ISSUE THREAD

**Issue by pbrisbin** [commercialhaskell/stack#4360]
### Steps to reproduce

1. Set up a repro project with `stack new --bare repro`
1. Add a file `templates/example.hamlet`

   ```html
   <h1>Hi
   ```

1. Update `Lib.hs` to

   ```hs
   {-# LANGUAGE TemplateHaskell #-}

   module Lib
      ( someFunc
      ) where

   import Text.Blaze.Html.Renderer.Pretty
   import Text.Hamlet

   someFunc :: IO ()
   someFunc = putStrLn $ renderHtml $(shamletFile "templates/example.hamlet")
   ```

   (Add the `shakespeare`and `blaze-html` dependencies as necessary.)

1. Start up `stack build --file-watch`

1. Modify the contents of `templates/example.hamlet`

### Expected

Modifying `templates/example.hamlet` should trigger re-compilation.

### Actual

It does not. However, if I add

```yaml
extra-source-files:
  - templates/*
```

To `package.yaml`, it works as expected. This should not be necessary as this packaging field is only documented as related to including files in `sdist`, not as a requirement for `qAddDependentFile` to work.

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

https://aur.archlinux.org/packages/stack-static/

### Notes

It's definitely an assumption on my part that this boils down to `qAddDependentFile`. So I apologize if that's not actually the case. Another way to phrase it could be, _external files referenced in TemplateHaskell don't cause re-compilation..._.

I've reproduced this bug with pretty much every file-reading TH function in a standard Yesod app (`parseRoutesFile`, `widgetFile`, etc).

I wouldn't have guessed this was Stack's responsibility either, but `cocreature` in `#haskell` encouraged me to report this bug here.

**Comment by dbaynard** [comment]
Thanks for the report. You may wish to try the new release of `stack` but I suspect this hasn't changed.

>  this packaging field is only documented as related to including files in sdist

This is the `Cabal` documentation, right?

@snoyberg how should we proceed?

**Comment by pbrisbin** [comment]
@dbaynard 

> This is the Cabal documentation, right?

Yeah, I was referring to this: https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-extra-source-files

**Comment by dbaynard** [comment]
@pbrisbin Do check the new version, when you get a chance — that should fix it.

**Comment by pbrisbin** [comment]
Unfortunately, this still reproduces for me with 1.9.

![](https://files.pbrisbin.com/screenshots/screenshot.31384.png)

(In the upper-right you can see me modifying the template, but no re-compilation happens in the lower-right.)

**Comment by dbaynard** [comment]
Ok, I can reproduce

**Comment by snoyberg** [comment]
The change that should fix this is only on the master branch, not on 1.9.

**Comment by ygale** [comment]
It's this commit: https://github.com/commercialhaskell/stack/commit/aae15e3

I wishfully submitted #4369, hoping that this small but important fix might be patched to 1.9.3.

**Comment by ygale** [comment]
Unfortunately, it appears that fix does not solve this issue.

In GHC 8.2 and earlier, the `.dump-hi` file contains `addDependentFile` lines for the TH files. That is no longer the case in GHC 8.4.

**Comment by ygale** [comment]
Hmm shakespeare explicitly reports its files to GHC as dependent files. This is starting to look like a GHC bug. I will investigate further.

**Comment by tolysz** [comment]
@ygale only the version `shakespeare-2.0.19`+ will report it.

**Comment by ygale** [comment]
@tolysz Ahh yes that was it. Thanks!!

In summary: To resolve this issue you need:

* stack >= 1.9.3
* shakespeare >= 2.0.19

As of this writing stack 1.9.3 is not yet released. For now, you can build stack 1.9.2 from the [stable branch](https://github.com/commercialhaskell/stack/tree/stable) on github and it will work.

If you use Stackage LTS, upgrade to at least [12.14](https://www.stackage.org/lts-12.14), currently the latest, to get the right version of shakespeare. Or specify `shakespeare-2.0.19` in the `extra-deps` section of your `stack.yaml`.

A million thanks to the stack team for getting this fixed!
